// Copyright (c) 2025 Dawid Szoldra. All rights reserved.

#pragma once

#include "NativeGameplayTags.h"
#include "CoreMinimal.h"

/**
 * GSGameplayTags
 *
 */
namespace GSGameplayTags
{
	namespace Input
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(LeftShift);
        UE_DECLARE_GAMEPLAY_TAG_EXTERN(Spacebar);
        UE_DECLARE_GAMEPLAY_TAG_EXTERN(LMB);
	}

	namespace Attributes
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_VIT);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_INT);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_STR);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_DEX);
	
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Primary_HP);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Primary_MaxHP);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Primary_HPRegen);
	
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Primary_PE);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Primary_MaxPE);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Primary_PERegen);
	
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Primary_ST);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Primary_MaxST);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Primary_STRegen);
	
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Primary_AttackDamage);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Primary_AttackDamageMin);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Primary_AttackDamageMax);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Primary_MagicDamage);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Primary_MagicDamageMin);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Primary_MagicDamageMax);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Primary_AttackSpeed);
	
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Primary_Defence);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Primary_MagicDefence);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Primary_Evading);

		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Others_XP);
	}

	namespace Statuses
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ST_Regen);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ST_Consuming);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ST_Zero);

		UE_DECLARE_GAMEPLAY_TAG_EXTERN(HP_Regen);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(HP_Consuming);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(HP_Zero);

		UE_DECLARE_GAMEPLAY_TAG_EXTERN(PE_Regen);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(PE_Consuming);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(PE_Zero);
	
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Forbidden);
	}
	/** ABILITIES **/
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_GA_Sprint);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Requires_ST);

	namespace Events
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Movement_Stopped);

		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Montage_Combo_Window);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Montage_Combo_Window_Start);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Montage_Combo_Window_End);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Montage_Combo_Trace);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Montage_Combo_Trace_Start);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Montage_Combo_Trace_End);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Montage_Combo_EnableMovement);
	}

};



